name: Update Events from YouTube

on:
  schedule:
    - cron: "0 0 * * 0" # 12:00 AM Sunday each week
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-youtube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          cd projects/1.2-committee-youtube/python/
          pip install .

      - name: YouTube Fetch
        run: python projects/1.2-committee-youtube/python/congress_youtube/youtube/fetch/main.py --youtube-api-key ${{ secrets.YOUTUBE_DATA_API_KEY }}

      - name: YouTube Analyze
        run: python projects/1.2-committee-youtube/python/congress_youtube/youtube/analyze/main.py

      - name: Upload to GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add projects/1.2-committee-youtube/data/*
          git commit -m "Updated Events from YouTube" || echo "No changes"
          git push
